### ISSUE TITLE
sems-yeti config ERROR: missed 'cdr_completed_dir'' parameter

### ISSUE THREAD

**Issue by summitrabz** [yeti-switch/sems-yeti#7]
Hi team,

I tried to post this error in the community forum, but there seems to be an https issue with opening the community forum page.

Here is the error I'm seeing with sems-yeti 1.9

I was testing failover to file config and sems could not start due to some missing parameter in cdr_completed_dir

yeti/system.cfg
..........
failover_requeue = true
failover_to_file = true
serialize_dynamic_fields = true
batch_size = 1
batch_timeout = 5000
..........

systemctl restart yeti-management restart
systemctl restart sems

sems/sems.log
sems[11935]:  [11935/11935] [yeti:SqlRouter.cpp:230] INFO: SqlRouter::db_configure: config successfuly readed
sems[11935]:  [11935/11935] [yeti:cdr/CdrWriter.cpp:873] ERROR: missed 'cdr_completed_dir'' parameter
sems[11935]:  [11935/11935] [yeti:SqlRouter.cpp:244] INFO: Cdr writer pool config loading error
sems[11935]:  [11935/11935] [yeti:yeti.cpp:354] ERROR: SqlRouter configure failed
sems[11935]:  [11935/11935] [yeti:SBC.cpp:119] ERROR: yeti configuration error

**Comment by furmur** [comment]
Hi,

it's an obsolete reply, but i will write it here to close the issue.

Failover to file is not supported for years because it was not used in any real setup.

missed:
```
    cdr {
        completed_dir = /var/spool/sems/cdrs/completed
    }
```
in `system.cfg` for your exact case. (or `cdr_completed_dir` for elder yeti-management versions with plain config)

But we also dropped the management node usage in the new versions so it's better to use fresh versions and a secondary DB connection for failover.

Also, you can request for failover to file as a new feature with your vision of how it may work and we would implement it from scratch.
